name: vasudha
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2   # ✅ Added for profile image upload (works on mobile & web)
  file_picker: ^8.0.0
  http: ^1.5.0
  shared_preferences: ^2.5.3
  fluttertoast: ^9.0.0
  share_plus: ^12.0.0
  whatsapp_share2: ^2.1.1 
  fl_chart: ^1.1.1
  font_awesome_flutter: ^10.10.0
  screenshot: ^3.0.0
  pdf: ^3.10.8
  printing: ^5.14.2
  url_launcher: ^6.3.2
  path_provider: ^2.1.3



dependency_overrides:
  pdf: 3.10.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/fonts/NotoSans-Regular.ttf
    - assets/fonts/NotoSans-Bold.ttf
    - assets/fonts/NotoColorEmoji.ttf

fonts:
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
    - family: NotoColorEmoji
      fonts:
        - asset: assets/fonts/NotoColorEmoji.ttf